-- MySQL Script generated by MySQL Workbench
-- Mon Apr  4 21:25:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema spotify_like
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema spotify_like
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `spotify_like` DEFAULT CHARACTER SET utf8mb4 ;
USE `spotify_like` ;

-- -----------------------------------------------------
-- Table `spotify_like`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `tipo` ENUM('free', 'premium') NULL,
  `email` VARCHAR(60) NULL,
  `password` VARCHAR(45) NULL,
  `nombre_usuario` VARCHAR(45) NULL,
  `fecha_nacimiento` DATETIME NULL,
  `genero` ENUM('hombre', 'mujer', 'no indicado') NULL,
  `pais` VARCHAR(45) NULL,
  `cp` VARCHAR(10) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`suscripciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`suscripciones` (
  `idsuscripcion` INT NOT NULL AUTO_INCREMENT,
  `fecha_inicio` DATETIME NULL,
  `fecha_renovacion` DATETIME NULL,
  `forma_pago` ENUM('tarjeta', 'PayPal') NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idsuscripcion`),
  INDEX `fk_suscripciones_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_suscripciones_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `spotify_like`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`metodos_pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`metodos_pago` (
  `idmetodopago` INT NOT NULL AUTO_INCREMENT,
  `Numero_targeta` INT NULL,
  `mes_cad_targeta` SMALLINT NULL,
  `ano_cad_targeta` YEAR(4) NULL,
  `codigo_seg_targeta` SMALLINT NULL,
  `usuario_paypal` VARCHAR(45) NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idmetodopago`),
  INDEX `fk_metodos_pago_usuarios_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_metodos_pago_usuarios`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `spotify_like`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`pagos` (
  `numero_pedido` INT NOT NULL,
  `fecha` DATETIME NULL,
  `pagoscol` VARCHAR(45) NULL,
  `total` DECIMAL NULL,
  `usuarios_idusuario` INT NOT NULL,
  `metodos_pago_idmetodopago` INT NOT NULL,
  PRIMARY KEY (`numero_pedido`),
  INDEX `fk_pagos_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  INDEX `fk_pagos_metodos_pago1_idx` (`metodos_pago_idmetodopago` ASC) VISIBLE,
  CONSTRAINT `fk_pagos_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `spotify_like`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_metodos_pago1`
    FOREIGN KEY (`metodos_pago_idmetodopago`)
    REFERENCES `spotify_like`.`metodos_pago` (`idmetodopago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`playlists`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`playlists` (
  `idplaylist` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `num_canciones` INT NULL,
  `fecha_creacion` DATETIME NULL,
  `fecha_eliminacion` DATETIME NULL,
  `estado` ENUM('Activa', 'Eliminada') NULL,
  PRIMARY KEY (`idplaylist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`playlist_compartida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`playlist_compartida` (
  `idplaylist_compartida` INT NOT NULL AUTO_INCREMENT,
  `playlists_idplaylist` INT NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idplaylist_compartida`),
  INDEX `fk_playlist_compartida_playlists1_idx` (`playlists_idplaylist` ASC) VISIBLE,
  INDEX `fk_playlist_compartida_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_compartida_playlists1`
    FOREIGN KEY (`playlists_idplaylist`)
    REFERENCES `spotify_like`.`playlists` (`idplaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_playlist_compartida_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `spotify_like`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`artistas_relacionados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`artistas_relacionados` (
  `idartista_relacionado` INT NOT NULL AUTO_INCREMENT,
  `artistas_idartista` INT NOT NULL,
  PRIMARY KEY (`idartista_relacionado`),
  INDEX `fk_artistas_relacionados_artistas1_idx` (`artistas_idartista` ASC) VISIBLE,
  CONSTRAINT `fk_artistas_relacionados_artistas1`
    FOREIGN KEY (`artistas_idartista`)
    REFERENCES `spotify_like`.`artistas` (`idartista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`artistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`artistas` (
  `idartista` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  `imagen_url` VARCHAR(120) NULL,
  `artistas_relacionados_idartista_relacionado` INT NOT NULL,
  PRIMARY KEY (`idartista`),
  INDEX `fk_artistas_artistas_relacionados1_idx` (`artistas_relacionados_idartista_relacionado` ASC) VISIBLE,
  CONSTRAINT `fk_artistas_artistas_relacionados1`
    FOREIGN KEY (`artistas_relacionados_idartista_relacionado`)
    REFERENCES `spotify_like`.`artistas_relacionados` (`idartista_relacionado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`favs_albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`favs_albums` (
  `idfav_album` INT NOT NULL AUTO_INCREMENT,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`idfav_album`),
  INDEX `fk_favs_albums_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_favs_albums_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `spotify_like`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`albums` (
  `idAlbum` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  `ano_publicacion` YEAR(4) NULL,
  `imagen_url` VARCHAR(120) NULL,
  `artistas_idartista` INT NOT NULL,
  `favs_albums_idfav_album` INT NOT NULL,
  PRIMARY KEY (`idAlbum`),
  INDEX `fk_albums_artistas1_idx` (`artistas_idartista` ASC) VISIBLE,
  INDEX `fk_albums_favs_albums1_idx` (`favs_albums_idfav_album` ASC) VISIBLE,
  CONSTRAINT `fk_albums_artistas1`
    FOREIGN KEY (`artistas_idartista`)
    REFERENCES `spotify_like`.`artistas` (`idartista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_albums_favs_albums1`
    FOREIGN KEY (`favs_albums_idfav_album`)
    REFERENCES `spotify_like`.`favs_albums` (`idfav_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`canciones` (
  `idcancion` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(60) NULL,
  `duracion` TIME NULL,
  `reproducciones` INT NULL,
  `albums_idAlbum` INT NOT NULL,
  PRIMARY KEY (`idcancion`),
  INDEX `fk_canciones_albums1_idx` (`albums_idAlbum` ASC) VISIBLE,
  CONSTRAINT `fk_canciones_albums1`
    FOREIGN KEY (`albums_idAlbum`)
    REFERENCES `spotify_like`.`albums` (`idAlbum`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`items_playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`items_playlist` (
  `iditem_lista` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `items_listacol` VARCHAR(45) NULL,
  `canciones_idcancion` INT NOT NULL,
  `playlists_idplaylist` INT NOT NULL,
  `usuarios_idusuario` INT NOT NULL,
  PRIMARY KEY (`iditem_lista`),
  INDEX `fk_items_playlist_canciones1_idx` (`canciones_idcancion` ASC) VISIBLE,
  INDEX `fk_items_playlist_playlists1_idx` (`playlists_idplaylist` ASC) VISIBLE,
  INDEX `fk_items_playlist_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_items_playlist_canciones1`
    FOREIGN KEY (`canciones_idcancion`)
    REFERENCES `spotify_like`.`canciones` (`idcancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_playlist_playlists1`
    FOREIGN KEY (`playlists_idplaylist`)
    REFERENCES `spotify_like`.`playlists` (`idplaylist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_playlist_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `spotify_like`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`follows_artistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`follows_artistas` (
  `idfollow_artista` INT NOT NULL AUTO_INCREMENT,
  `usuarios_idusuario` INT NOT NULL,
  `artistas_idartista` INT NOT NULL,
  PRIMARY KEY (`idfollow_artista`),
  INDEX `fk_follows_artistas_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  INDEX `fk_follows_artistas_artistas1_idx` (`artistas_idartista` ASC) VISIBLE,
  CONSTRAINT `fk_follows_artistas_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `spotify_like`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_follows_artistas_artistas1`
    FOREIGN KEY (`artistas_idartista`)
    REFERENCES `spotify_like`.`artistas` (`idartista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `spotify_like`.`favs_canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `spotify_like`.`favs_canciones` (
  `idfav_cancion` INT NOT NULL AUTO_INCREMENT,
  `usuarios_idusuario` INT NOT NULL,
  `canciones_idcancion` INT NOT NULL,
  PRIMARY KEY (`idfav_cancion`),
  INDEX `fk_favs_canciones_usuarios1_idx` (`usuarios_idusuario` ASC) VISIBLE,
  INDEX `fk_favs_canciones_canciones1_idx` (`canciones_idcancion` ASC) VISIBLE,
  CONSTRAINT `fk_favs_canciones_usuarios1`
    FOREIGN KEY (`usuarios_idusuario`)
    REFERENCES `spotify_like`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favs_canciones_canciones1`
    FOREIGN KEY (`canciones_idcancion`)
    REFERENCES `spotify_like`.`canciones` (`idcancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
